### ISSUE TITLE
InsightViewer component is imported as an object.

### ISSUE THREAD

**Issue by zzoman** [lunit-io/frontend-components#185] opened 2022-01-21 06:47 UTC
We are trying to use new version of insight-viewer for making our CTL can support CT project.
But for the CXR/MMG project, we are using previous version of insight-viewer, so we tried to using multiple versions of package at the same time.

```json
"dependencies": {
  "@hookform/resolvers": "^2.8.0",
  "@lunit/insight-viewer": "^4.4.1",
  "@lunit/insight-viewer-new": "npm:@lunit/insight-viewer@latest",
}
``` 

We used just `latest` version of insight-viewer for new one because we don't know which one is stable version yet. And it seems the version `5.1.0-alpha.7` was installed as a latest one.

```
"@lunit/insight-viewer-new@npm:@lunit/insight-viewer@latest":
  version "5.1.0-alpha.7"
  resolved "https://registry.yarnpkg.com/@lunit/insight-viewer/-/insight-viewer-5.1.0-alpha.7.tgz#ed1f12bebdf590af9218ec4c6826463a917071a5"
  integrity sha512-dGpO1NCi0i/DDgFniprmcrcYdSCSFNIfppfuRXQUEcfcEMcCcmx0P4pWlSlKWkC9adGoL2uU8jPvWh7Dnb4s9g==
  dependencies:
    uid "^2.0.0"
    consola "2.15.3"
    cornerstone-core "^2.3.0"
    cornerstone-wado-image-loader "^3.3.1"
    cornerstone-web-image-loader "^2.1.1"
    dicom-parser "^1.8.7"
    ky "^0.27.0"
    point-in-polygon "^1.1.0"
    react-resize-detector "^6.7.0"
    rxjs "^7.0.0"
```

With import of that version, we caught follow error.

![image](https://user-images.githubusercontent.com/85869089/150478165-9fea46a9-ac82-4549-90cd-c5fbacde23ca.png)

And it seems the imported `InsightViewer` was actually an object.

![image](https://user-images.githubusercontent.com/85869089/150478267-80d19541-8690-448f-ad36-b8cdae662242.png)

It can be a problem from usage of multiple versions, so we tried it with a new created react package, but it happens too.

So I contacted to @skpark-lunit for to figure out which version is stable for use, and she shared [codesandbox example](https://codesandbox.io/s/insight-viewer-multiframe-mkz4n?file=/src/App.tsx) which was using version `5.1.0-alpha.0` and it was working perfectly.

So finally, it looks like it is the problem of new version's build, and making this issue for request to fix it :)

**Comment by skpark-lunit** [comment] 2022-01-21 08:07
v.5.1.0-alpha.0 has no default export which is meant to be Insight Viewer React component.
<img width="664" alt="무제" src="https://user-images.githubusercontent.com/81394944/150489141-687f37d9-6e41-4038-9d09-bc58087a4e23.png">
I think the issue is caused by multiple entry modules with exports field in package.json.
```
import InsightViewer from "@lunit/insight-viewer";

function App() {
    return (
        <InsightViewer.default image={image} />
    )
}
```
It works, not I expected though.

**Comment by skpark-lunit** [comment] 2022-01-21 09:22
https://github.com/lunit-io/frontend-components/pull/173 intended the final published file structure in node_modules as below.
<img width="330" alt="무제" src="https://user-images.githubusercontent.com/81394944/150500729-a190c0a0-9ae6-41b6-944e-c29e977bbefa.png">
But it becomes like this when v.5.1.0-alpha.7 is installed by yarn add command.
<img width="433" alt="무제2" src="https://user-images.githubusercontent.com/81394944/150500897-9783bca2-9a39-4710-a9be-4b701b36b72f.png">

Lerna publish command might not have worked properly.

**Comment by deminoth** [comment] 2022-02-22 06:16
Closed by https://github.com/lunit-io/frontend-components/pull/190

**Closed by deminoth** 2022-02-22 06:16 UTC
Labels: bug
